### ISSUE TITLE
[Fix] 앱 안정화 작업 및 수정사항 적용

### ISSUE THREAD

**Issue by TakeMos** [DeveloperAcademy-POSTECH/2024-MacC-M4-6princess#103]
## 🛠 Issue

누끼를 따는 뷰에서 넘어갈 때에 누끼를 편집한 것이 즉각 반영되지 않는 부분, 빌드 후 첫 실행 시 누끼가 제대로 넘어가지 않는 등의 문제를  수정할 예정입니다.
## 📝 To-do

- [ ] 누끼 편집 적용 문제 개선
- [x] 누끼가 제대로 넘어가지 않는 문제 개선
- [ ] 수정이 제대로 적용되지 않는 문제 개선
