### ISSUE TITLE
[Fix] 레이어 ForEach 문 && 텍스트 수정

### ISSUE THREAD

**Issue by piriram** [DeveloperAcademy-POSTECH/2024-MacC-M4-6princess#111]
## 📝 To-do

- [ ] 레이어 ForEach 문제 해결
- [ ] 텍스트뷰 디자인 수정
- [ ] 텍스트 수정 기능 구현
- [ ] 아이패드뷰 확인
