### ISSUE TITLE
[Feat] 프레임 수정 구현

### ISSUE THREAD

**Issue by TakeMos** [DeveloperAcademy-POSTECH/2024-MacC-M4-6princess#117]
## 📝 To-do

- [ ] 코어데이터 스키마 수정
- [ ] 코어데이터 저장 수정
- [ ] 코어데이터 불러오기 수정
