### ISSUE TITLE
[Fix] 프레임 foreach문 개선

### ISSUE THREAD

**Issue by piriram** [DeveloperAcademy-POSTECH/2024-MacC-M4-6princess#125]
## 📝 To-do

- [ ] 프레임 foreach문 개선
- [ ] 수정 확대 기능 변경
- [ ] 시간나면 리팩토링,,,선택박스 특히
