### ISSUE TITLE
[Feat]이미지 편지 기능 구현

### ISSUE THREAD

**Issue by piriram** [DeveloperAcademy-POSTECH/2024-MacC-M4-6princess#3]
### ImageEdit 이미지 편집 기능 
**프레임만들기**
- 프레임 가로세로 전환
- 프레임 크기 수정/이동/삭제 
**촬영후편집**
- 밝기, 채도, 대비 수정 기능 → CoreImage

- 화면 확대/축소→Magnify Gesture -> IEMagnifyGestureTestView

- 사진 확대/축소 -> 내 카메라 & 최애 누끼 
- 사진 각도 수정

Undo/Redo
## 📝 To-do

- [x] MagnifyGesture 구현(UIImage 사용)
- [x] 사진 템플릿 width를 핸드폰 가로사이즈에 맞추기
- [x] 사진 크기를 4:3과 16:9로 지정
- [x] 테스트 사진+최애 사진 넣기
- [x] 테스트 사진 위에 최애 사진 올리기
- [x] 최애 누끼 위치 및 크기 조정
- [x] CoreImage를 통한 색감조정
- [ ] 테스트 사진과 최애 사진을 각각 색감 조절하기
- [x] 코드 다듬기
