### ISSUE TITLE
[Fix] 내부 쇼케이스 이후 결함 수정

### ISSUE THREAD

**Issue by piriram** [DeveloperAcademy-POSTECH/2024-MacC-M4-6princess#34]
## 🛠 Issue

내부 쇼케이스 이후 결함 수정
## 📝 To-do

- [ ] 편집화면에서 누끼의 이동 범위 수정
- [ ] 확대 및 축소의 속도 조절
- [ ] 사진의 비율 일그러짐 수정
