### ISSUE TITLE
[Fix] 내부쇼케이스 이후 수정사항

### ISSUE THREAD

**Issue by TakeMos** [DeveloperAcademy-POSTECH/2024-MacC-M4-6princess#36]
## 🛠 Issue

쇼케이스 이후 발생한 수정사항 중에서 우선순위가 높은 것들을 적용을 할 예정입니다.
## 📝 To-do

- [x] 누끼 편집할 때 확대 및 축소
- [x] 누끼 회전 문제
- [x] 프레임을 만들고 나면 카메라에서 바로 볼 수 있도록 수정
- [x] 저장하기 버튼 수정
