### ISSUE TITLE
[Feat] 타이머 및 찍는 횟수 설정

### ISSUE THREAD

**Issue by darongzzang** [DeveloperAcademy-POSTECH/2024-MacC-M4-6princess#5]
## 🛠 Issue

카메라 뷰에 타이머 기능과 찍는 횟수를 설정할 수 있도록 개발합니다.

## 📝 To-do

- [x] 타이머 기능 넣기
- [x] 코드 리팩토링이 필요한지 생각
- [ ] 찍는 횟수 설정 구현하기
