### ISSUE TITLE
[Feat] 카메라 줌인/줌아웃

### ISSUE THREAD

**Issue by darongzzang** [DeveloperAcademy-POSTECH/2024-MacC-M4-6princess#51]
## 🛠 Issue

카메라뷰에서 줌인/줌아웃을 할 수 있게 개발합니다

## 📝 To-do

- [x] 카메라 줌인 줌아웃 제스처 알아보기
- [ ] 전면은 기본 0.8배, 줄이면 0.5배?로 생각하고 개발해보기
- [x] 후면은 기본 1배, 0.5, 2, 3배까지 지원하도록
