### ISSUE TITLE
[Feat] 다중 누끼 관련 구현

### ISSUE THREAD

**Issue by TakeMos** [DeveloperAcademy-POSTECH/2024-MacC-M4-6princess#57]
## 🛠 Issue

다중 누끼 추가 및 편집 구현
## 📝 To-do

- [x] 프레임을 선택하면 선택한 프레임에 오버레이 박스 씌우기
- [x] 오버레이 박스의 위치 수정 구현
- [x] 오버레이 박스의 스케일 변화 구현
- [x] 오버레이 박스의 회전 기능 구현
- [x] 다수의 누끼 추가 기능
- [x] 프레임 만들기 뷰 수정
