### ISSUE TITLE
[Feat] 누끼 생성 및 편집 기능 구현

### ISSUE THREAD

**Issue by TakeMos** [DeveloperAcademy-POSTECH/2024-MacC-M4-6princess#6]
## 🛠 Issue
누끼를 생성하기 위해서 필요한 mask를 편집하고 적용하는 기능을 구현합니다.

## 📝 To-do

- [x] 누끼를 위한 마스크 생성
- [x] 마스크를 편집하는 기능(브러쉬 및 지우개)
- [x] 브러쉬와 지우개의 굵기 설정
- [x] 따진 누끼 미리보기
- [x] 누끼를 따서 저장
