### ISSUE TITLE
[Chore] 카메라뷰 QA 바탕으로 수정

### ISSUE THREAD

**Issue by darongzzang** [DeveloperAcademy-POSTECH/2024-MacC-M4-6princess#8]
## 🛠 Issue

- 카메라의 default 설정을 전면으로 변경합니다.
- 프레임 선택 뷰에 이미지가 없을 때 띄우는 뷰를 추가합니다.
- firstTime 변수의 프로퍼티 래퍼를 변경합니다 (@State -> @AppStorage, 온보딩에 쓰이기 때문)
- 프레임선택 뷰에서 자연스럽게 포토스피커 뷰로 넘어갈 수 있도록 수정합니다.

## 📝 To-do

- [x] 카메라의 default 설정을 전면으로 변경
- [ ] 프레임선택뷰 EmptyView 추가
- [ ] 변수 프로퍼티 래퍼 바꾸기
- [ ] '새로운 프레임 만들기' 눌렀을 때 모달 내리고 풀스크린으로 다른 뷰 띄우기
